name: Deploy to Development

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  CI: false
  NAME: 'Yogesh Nikam'

jobs:
  build:
    name: Build and Deploy to Development
    runs-on: ubuntu-latest

    steps:
      - name: Print Name
        run:  echo "Hellow $NAME"
        
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Run Tests with Coverage
        run: npm run test

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage  # Jest outputs to ./coverage by default

      - name: Build Application
        run: npm run build --if-present

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: development-build
          path: ./build  # Update this path if your build output differs
