name: Deploy to Development

on:
  push:
    branches: ["main"]

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4  # ✅ Fixed indentation

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build with development config
        run: npm run build

      - name: Upload production Ready Build
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build  # ✅ Make sure this matches your actual output dir (maybe ./public if using Webpack directly)
