name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build with development config
        run: npm run build:dev

      - name: Deploy to S3 (Development)
        run: aws s3 sync build/ s3://my-react-dev-bucket --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
